### ISSUE TITLE
编译时出现RawImage.h中出现SD/Seeed_SD.h: No such file or directory

### ISSUE THREAD

**Issue by CofinCup** [KafCoppelia/WioWeatherStation#1]
我刚开始使用arduino，对arduino的import结构不是很熟悉；
但是我尝试了多种方法，似乎都没能让“SD”被认为是wio terminal给的SD卡读取库文件夹下的SD，因而无法编译

**Comment by KafCoppelia** [comment]
好像要给Wio安装SD相关的库
